version: "0.2"
dictionaries:
  - project-words
  - typescript
  - english
  - ethereum
  - bash
  - linux
  - node
dictionaryDefinitions:
  - name: project-words
    path: ./project-words.txt
    addWords: true
ignorePaths:
  - ".github/renovate.json"
  - "**/dist/**"
  - "**/assets/**"
  - "*.svg"
  - "patches/**"
  - "examples/pay-demo/build/**"
  - "apps/idos-data-dashboard/build/**"
  - "pnpm-lock.yaml"
  - "package.json"
  - ".turboignore"
  - "cspell.config.yaml"
  - "**/.gitignore"
  - "**/tsconfig.tsbuildinfo"
  - "**/playwright-report/**"
  - "apps/facesign-enclave/public/facetec/**"
